### ISSUE TITLE
Cannot find module './ngx-calculator/ngx-calculator.module'

### ISSUE THREAD

**Issue by bemonio** [lucashsilva/ngx-calculator#1]
error import module:
Cannot find module './ngx-calculator/ngx-calculator.module'

I'm using angular 4.2

**Comment by lucasasenna** [comment]
Hello @bemonio, thanks for opening this issue. I just released the version 1.0.8, which fixes this problem.
You should replace `import { NgxCalculatorModule } from './ngx-calculator/ngx-calculator.module';` with `import { NgxCalculatorModule } from 'ngx-calculator';`. This was a doc mistake.

**Comment by shyamsunderprasad** [comment]
I am getting error like :ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-calculator/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
Please help.
I used
 import { NgxCalculatorModule } from 'ngx-calculator';
